### ISSUE TITLE
The interface should have an editor with an easy way to "insert a question here"

### ISSUE THREAD

**Issue by vsoch** [vsoch/askci#15]
This would come down to adding a custom button to the editor (need to look into this).

**Comment by vsoch** [comment]
The example to add a custom button and event is here:

https://github.com/nhn/tui.editor/blob/master/examples/example11-customize-toolbar.html#L89

And I'm waiting to hear from maintainers about how to index where the cursor is inside the editor

https://github.com/nhn/tui.editor/issues/697

Putting those three things together should be fairly easy!

**Comment by vsoch** [comment]
This is all set, forgot to close the issue.

**Comment by livevsonline** [comment]
> The example to add a custom button and event is here:
> 
> https://github.com/nhn/tui.editor/blob/master/examples/example11-customize-toolbar.html#L89
> 
> And I'm waiting to hear from maintainers about how to index where the cursor is inside the editor
> 
> [nhn/tui.editor#697](https://github.com/nhn/tui.editor/issues/697)
> 
> Putting those three things together should be fairly easy!

The sample does not work anymore
